#! /bin/zsh

PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=26
PANEL_FONT_FAMILY="-*-fixed-*-*-*-*-12-*-*-*-*-*-*-*"
ICON_FONT="-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1"
export PANEL_FIFO PANEL_HEIGHT PANEL_FONT_FAMILY
source $(dirname $0)/panel_colors


if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi


trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc subscribe report > "$PANEL_FIFO" &
#xtitle -sf 'T%s' > "$PANEL_FIFO" &

# pac
while true;
    do
        echo 'A\ue00f' $(checkupdates | wc -l)
    sleep 180;
done > "$PANEL_FIFO" &

# mem
while true;
    do
        echo 'M\ue020' $(free -h | grep Mem: | awk '{print $3}');
    sleep 5;
done > "$PANEL_FIFO" &

# clock
while true;
	do
        echo 'C\ue017' $(clock);  
	sleep 5;
done > "$PANEL_FIFO" &

# net 
while true;
do
       echo 'E\ue21a' $(ethtool enp3s0 | grep "Link detected:" | sed s/"Link detected:"// | xargs);
    sleep 5;
done > $PANEL_FIFO &


# mail
while true;
do
       echo 'D\ue072' $(/home/tiago/.config/bspwm/panel/mail.sh );
    sleep 5;
done > $PANEL_FIFO &


# weather
while true;
do
       echo 'J' $(/home/tiago/.config/bspwm/panel/weather.sh );
    sleep 5;
done > $PANEL_FIFO &

# vol 
while true;
do
ALSA_VOLUME=$(amixer get Master | grep 'Mono: Playback' | grep -o '...%' | sed 's/\[//' | sed 's/%//' | sed 's/ //')
ALSA_STATE=$(amixer get Master | grep 'Mono: Playback' | grep -o '\[on]')

if [ $ALSA_STATE ]
then
	if [ $ALSA_VOLUME -ge 70 ]
	then
		echo V'\ue05d' $ALSA_VOLUME
	fi
	if [ $ALSA_VOLUME -gt 0 -a $ALSA_VOLUME -lt 70 ]
	then
		echo V'\ue050' $ALSA_VOLUME
	fi
	if [ $ALSA_VOLUME -eq 0 ]
	then
		echo V'\ue04e' $ALSA_VOLUME
	fi
	else
		echo V'\ue04f' $ALSA_VOLUME
	fi
	sleep 0.1
done > $PANEL_FIFO &

# music controls
while true;
do
	cur=$(mpc | head -n1)
	if [[ -n $(mpc status | grep paused) ]]
	then
		echo "R%{T3}%{A:mpc prev:}\ue055%{A} %{A:mpc play:}\ue058%{A}  %{A:mpc next:}\ue05b%{A}%{T1} $cur"
	else
		echo "R%{T3}%{A:mpc prev:}\ue055%{A} %{A:mpc pause:}\ue059%{A} %{A:mpc next:}\ue05b%{A}%{T1} $cur"
	fi

	sleep 1
done > $PANEL_FIFO &


panel_bar < "$PANEL_FIFO" |lemonbar -a 30 -n "$PANEL_WM_NAME" -g x$PANEL_HEIGHT  -f "$PANEL_FONT_FAMILY" -f "$ICON_FONT"  -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" | sh &

wid=$(xdo id -a "$PANEL_WM_NAME")
tries_left=20
while [ -z "$wid" -a "$tries_left" -gt 0 ] ; do
    sleep 0.05
lemonbar -g 120x20+20+20    wid=$(xdo id -a "$PANEL_WM_NAME")
    tries_left=$((tries_left - 1))
done
[ -n "$wid" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
